name: build-test

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: JDK 17 Install
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 설정 파일 생성
        run: |
          echo "${{ secrets.APPLICATION_CONFIG_URLS }}" > ./src/main/resources/app-urls.yml
          echo "${{ secrets.APPLICATION_CONFIG_AUTHORIZATION }}" > ./src/main/resources/authorization-config.yml
          echo "${{ secrets.APPLICATION_CONFIG_DATABASE }}" > ./src/main/resources/db-config.yml
          echo "${{ secrets.APPLICATION_CONFIG_KAKAOMAP }}" > ./src/main/resources/kakao-config.yml
          echo "${{ secrets.APPLICATION_CONFIG_MAIL }}" > ./src/main/resources/mail-config.yml
          echo "${{ secrets.APPLICATION_CONFIG_MULTIPART }}" > ./src/main/resources/multipart-config.yml
          echo "${{ secrets.APPLICATION_CONFIG_OAUTH2 }}" > ./src/main/resources/oauth2-config.yml
          echo "${{ secrets.APPLICATION_CONFIG_S3 }}" > ./src/main/resources/s3-config.yml
          echo "${{ secrets.APPLICATION_CONFIG_SEOUL }}" > ./src/main/resources/seoul-config.yml
          echo "${{ secrets.APPLICATION_CONFIG_TMAP }}" > ./src/main/resources/t-config.yml

      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: 테스트 및 빌드
        run: ./gradlew clean build